# Please refer to https://dev.poktroll.com/operate/configs/relayminer_config for documentation.
default_signing_key_names:
  - key-for-supplier1
smt_store_path: /home/pocket/.poktroll/smt
pocket_node:
  query_node_rpc_url: tcp://full-node:26657
  query_node_grpc_url: tcp://full-node:9090
  tx_node_rpc_url: tcp://full-node:26657
suppliers:
  - service_id: "0021" # 0021 is an Ethereum mainnet service ID. Other legacy IDs: https://docs.pokt.network/reference/supported-chains
    service_config:
      backend_url: "" # Ethereum mainnet RPC endpoint to forward relays to. E.g. http://etherium-node:8547/
      publicly_exposed_endpoints:
        - YOUR_NODE_IP_OR_HOST # Hostname or IP address. You want this to match the address from the supplier stake config.
    listen_url: http://0.0.0.0:8545 # You can replace `0.0.0.0` with a different network interface if you don't want to open port on all network interfaces.
metrics:
  enabled: true
  addr: :9090
pprof:
  enabled: false
  addr: :6060
