global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'relay-miner'
    scheme: http
    static_configs:
      - targets: ['relayminer:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: relayminer

  - job_name: 'appgate'
    scheme: http
    static_configs:
      - targets: ['appgate:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: appgate

  - job_name: 'gateway'
    scheme: http
    static_configs:
      - targets: ['gateway:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: appgate

  - job_name: 'poktrolld'
    scheme: http
    metrics_path: /metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['poktrolld:1317']