global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'relay-miner'
    scheme: http
    static_configs:
      - targets: ['relayminer:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: relayminer

  - job_name: 'appgate'
    scheme: http
    static_configs:
      - targets: ['appgate:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: appgate

  - job_name: 'gateway'
    scheme: http
    static_configs:
      - targets: ['gateway:9090']
        labels:
          # For backwards-compatibility with LocalNet dashboard
          container: appgate

  - job_name: 'full-node'
    scheme: http
    metrics_path: /metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['full-node:1317']