{
 "title": "Protocol / AppGate Server",
 "tags": [ "protocol" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "appgateserver",
    "query": {
     "query": "label_values(go_info{container=\"appgate-server\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Relay info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (appgateserver_requests_total{job=~\"^$appgateserver.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (appgateserver_errors_total{job=~\"^$appgateserver.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Golang metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum (go_goroutines{job=~\"$appgateserver-.*\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}