{
 "title": "High level overview",
 "description": "An overarching dashboard that provides a high-level view of the entire infrastructure's health and performance by aggregating key metrics from all actors (Appgate, Gateway, RelayMiner, Full Node). This dashboard is essential for quickly assessing the network's status and identifying any potential issues.",
 "tags": [
  "network",
  "overview",
  "infrastructure"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (rpc_type, service_id)(rate(appgateserver_relay_requests_total[1m]))",
     "legendFormat": "Appgate {{rpc_type}} {{service_id}}"
    },
    {
     "expr": "sum by (rpc_type, service_id)(rate(relayminer_requests_total[1m]))",
     "legendFormat": "RelayMiner {{rpc_type}} {{service_id}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(100 * (sum(rate(appgateserver_relay_requests_success_total{job=\"appgate\"}[1m])) / sum(rate(appgateserver_relay_requests_total{job=\"appgate\"}[1m]))), 100)",
     "legendFormat": "AppGate"
    },
    {
     "expr": "clamp_max(100 * (sum(rate(appgateserver_relay_requests_success_total{job=\"gateway\"}[1m])) / sum(rate(appgateserver_relay_requests_total{job=\"gateway\"}[1m]))), 100)",
     "legendFormat": "Gateway"
    },
    {
     "expr": "clamp_max(100 * (sum(rate(relayminer_requests_success_total[1m])) / sum(rate(relayminer_requests_total[1m]))), 100)",
     "legendFormat": "RelayMiner"
    }
   ]
  },
  {
   "title": "Total Errors per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "sum by (rpc_type, service_id)(rate(appgateserver_relay_requests_errors_total[1m]))",
     "legendFormat": "Appgate {{rpc_type}} {{service_id}}"
    },
    {
     "expr": "sum by (service_id)(rate(relayminer_requests_errors_total[1m]))",
     "legendFormat": "RelayMiner {{service_id}}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (code, job, method, handler)(rate(http_response_size_bytes_sum[1m]))",
     "legendFormat": "{{job}} {{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{container=\"appgate\"}[1m]) ) by (method, handler)/sum( rate(http_request_duration_seconds_count{container=\"appgate\"}[1m]) ) by (method, handler)) * 1000 > 0",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_inflight", "legendFormat": "{{job}} {{handler}}" }
   ]
  },
  {
   "title": "Full Node Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_blocksync_syncing" }
   ]
  },
  {
   "title": "Full Node Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"appgate|gateway|relay-miner|full-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transactions per Block",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_consensus_num_txs", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage Across Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(process_cpu_seconds_total{job=~\"appgate|gateway|relay-miner|full-node\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage Across Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"appgate|gateway|relay-miner|full-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"appgate|gateway|relay-miner|full-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"appgate|gateway|relay-miner|full-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(go_gc_duration_seconds_sum{job=~\"appgate|gateway|relay-miner|full-node\"} / go_gc_duration_seconds_count{job=~\"appgate|gateway|relay-miner|full-node\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"appgate|gateway|relay-miner|full-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}