{
 "title": "Protocol / RelayMiner",
 "tags": [ "protocol" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "relayminer",
    "query": {
     "query": "label_values(go_info{container=\"relayminer\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Relay info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (relayminer_requests_total{job=~\"^$relayminer.*\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "relayminer_request_duration_seconds_bucket{job=~\"^$relayminer.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Golang metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$relayminer\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}