shannon_config:
  full_node_config:
    rpc_url: http://full-node:26657
    grpc_config:
      host_port: full-node:9090
      insecure: true
    lazy_mode: false
  gateway_config:
    gateway_mode: centralized
    gateway_address: YOUR_PATH_GATEWAY_ADDRESS
    gateway_private_key_hex: YOUR_PATH_GATEWAY_PRIVATE_KEY
    owned_apps_private_keys_hex:
      - YOUR_OWNED_APP_PRIVATE_KEY

services:
  # TODO_TECHDEBT(@Olshansk): Replace F00C with the final ethereum serviceID once determined (or anvil).
  "F00C":
    alias: "eth"